In [1]:
#numpy advanced
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(type(a))
print(a.shape)
print(type(b))
print(b.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(3,)


In [2]:
print(a[0],a[1],a[2])

1 2 3


In [3]:
a[0]=5
print(a)

[5 2 3]


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [5]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [6]:
import numpy as np
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [7]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [8]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [9]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [10]:
e=np.random.random((2,2))
print(e)

[[0.44756639 0.78655818]
 [0.96909423 0.24109158]]


In [11]:
import numpy as np
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [12]:
np.linspace(2.0,3.0,num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [13]:
np.linspace(2.0,3.0,num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [14]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print((a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
b=a[:2,1:3]
print((b))

[[2 3]
 [6 7]]


In [16]:
print(a[0,1])

2


In [17]:
print(a[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
print(a[:2,1:3])

[[2 3]
 [6 7]]


In [19]:
print(a[0:2,1:2])

[[2]
 [6]]


In [20]:
print(a[2:3,0:2])

[[ 9 10]]


In [21]:
print(a[:2,1:])

[[2 3 4]
 [6 7 8]]


In [22]:
print(a[-3:-1,-2:-1])

[[3]
 [7]]


In [23]:
print(a[-2:1,1:3])

[]


In [24]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [25]:
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [26]:
print(a[[0,0],[1,1]])

[2 2]


In [27]:
print(np.array([a[0,1],a[0,1]]))

[2 2]


In [28]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
b=np.array([0,2,0,1])
print(b)

[0 2 0 1]


In [31]:
print(a[np.arange(4),b])

[ 1  6  7 11]


In [32]:
a[np.arange(4),b]+=10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [33]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [34]:
print(a[bool_idx])

[3 4 5 6]


In [35]:
print(a[a>2])

[3 4 5 6]


In [36]:
import numpy as np
x=np.array([1,2])
print(x.dtype)

int32


In [37]:
x=np.array([1.0,2.0])
print(x.dtype)

float64


In [40]:
x=np.array([1,2],dtype=np.int64)
print(x.dtype)

int64


In [39]:
import numpy as np
a=np.array([[1,2],[3,4]])
eigenvalues,eigenvectors=np.linalg.eig(a)
print("eigenvalues:")
print(eigenvalues)
print("\n eigenvectors:")
print(eigenvectors)

eigenvalues:
[-0.37228132  5.37228132]

 eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [41]:
import numpy as np
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [42]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [43]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [44]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [45]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [46]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [47]:
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [48]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [49]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [50]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [51]:
print(x.T)

[[1 3]
 [2 4]]


In [52]:
v=np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]
